kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicacount}}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dep
    spec:
      containers:
      - image: ladekarpallav/hugo-app:{{.Values.tag}}
        name: {{ .Release.Name }}
        imagePullPolicy: {{ .Values.pullpolicy}}
        ports:
        - containerPort: {{ .Values.port}}
          protocol: TCP
