kind: Deployment 
apiVersion: extensions/v1beta1 
metadata: 
  name: apache 
spec: 
  replicas: {{.Values.scale}}  
  template: 
    metadata: 
      labels: 
        app: apache 
    spec: 
      containers: 
      - name: apache 
        image: ladekarpallav/public:{{.Values.tag}} 
        ports: 
        - containerPort: 80
